
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/*
 * @author Jose Luis Mora
 */
public class MainUIFrame extends javax.swing.JFrame {
    
    // Inicializa el DAO para los gimnasios
    GimnasioDAO gymDao = new GimnasioDAO();

    /**
     * Creates new form MainUIFrame
     */
    public MainUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloPrincipal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_anadirGimnasio = new javax.swing.JPanel();
        jLabel_nombre_gym = new javax.swing.JLabel();
        jTextField_nombre_gym = new javax.swing.JTextField();
        jLabel_cantidad_maquinas = new javax.swing.JLabel();
        jTextField_cantidad_maqinas = new javax.swing.JTextField();
        jCheckBox_crossfit = new javax.swing.JCheckBox();
        jLabel_cant_clientes = new javax.swing.JLabel();
        jTextField_cant_clientes = new javax.swing.JTextField();
        jButton_anadir_gym = new javax.swing.JButton();
        jPanel_listaGimnasios = new javax.swing.JPanel();
        jScrollPane_listaGimnasios = new javax.swing.JScrollPane();
        jTable_tablaListaGimnasios = new javax.swing.JTable(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        jButton_lista_actualiza = new javax.swing.JButton();
        jPanel_buscarGimnasios = new javax.swing.JPanel();
        jLabel_busqueda_nombre = new javax.swing.JLabel();
        jTextField_busqueda_nombre = new javax.swing.JTextField();
        jScrollPane_busqueda_gimnasios = new javax.swing.JScrollPane();
        jList_busqueda_nombre = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel_editar_id = new javax.swing.JLabel();
        jLabel_editar_nombre = new javax.swing.JLabel();
        jLabel_editar_maquinas = new javax.swing.JLabel();
        jLabel_editar_crossfit = new javax.swing.JLabel();
        jLabel_editar_promedio = new javax.swing.JLabel();
        jButton_buscar_nombre = new javax.swing.JButton();
        jTextField_editar_id = new javax.swing.JTextField();
        jTextField_editar_nombre = new javax.swing.JTextField();
        jTextField_editar_maquinas = new javax.swing.JTextField();
        jTextField_editar_promedio = new javax.swing.JTextField();
        jCheckBox_editar_crossfit = new javax.swing.JCheckBox();
        jButton_editar_guardar_cambios1 = new javax.swing.JButton();
        jPanel_busquedaPorClientes = new javax.swing.JPanel();
        jLabel_promedioMinimo = new javax.swing.JLabel();
        jTextField_promedioClientes = new javax.swing.JTextField();
        jButton_filtrarPorPromedio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList_busqueda_promedio = new javax.swing.JList<>();
        jPanel_ordenarGimnasios = new javax.swing.JPanel();
        jButton_ordenarNombre = new javax.swing.JButton();
        jButton_ordenarNumMaquinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloPrincipal.setText("Asociación Nacional de Gimnasios y Centros de Salud");

        jButton1.setText("Ok");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel_anadirGimnasio.setPreferredSize(new java.awt.Dimension(792, 329));

        jLabel_nombre_gym.setText("Nombre del Gimnasio");

        jLabel_cantidad_maquinas.setText("Cantidad de Máquinas");

        jCheckBox_crossfit.setText("Incluye Crossfit");
        jCheckBox_crossfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_crossfitActionPerformed(evt);
            }
        });

        jLabel_cant_clientes.setText("Cantidad promedio de clientes mensuales");

        jButton_anadir_gym.setText("Añadir Gimnasio");
        jButton_anadir_gym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anadir_gymMouseClicked(evt);
            }
        });
        jButton_anadir_gym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anadir_gymActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_anadirGimnasioLayout = new javax.swing.GroupLayout(jPanel_anadirGimnasio);
        jPanel_anadirGimnasio.setLayout(jPanel_anadirGimnasioLayout);
        jPanel_anadirGimnasioLayout.setHorizontalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombre_gym, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_cantidad_maquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                        .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre_gym, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox_crossfit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(jTextField_cantidad_maqinas, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_anadir_gym)
                                .addComponent(jTextField_cant_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 598, Short.MAX_VALUE))
                    .addComponent(jLabel_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_anadirGimnasioLayout.setVerticalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nombre_gym)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre_gym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cantidad_maquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cantidad_maqinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_crossfit)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cant_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cant_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_anadir_gym)
                .addContainerGap(393, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Añadir Gimnasio", jPanel_anadirGimnasio);

        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        jScrollPane_listaGimnasios.setViewportView(jTable_tablaListaGimnasios);

        jButton_lista_actualiza.setText("Actualizar Lista");
        jButton_lista_actualiza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_lista_actualizaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listaGimnasiosLayout = new javax.swing.GroupLayout(jPanel_listaGimnasios);
        jPanel_listaGimnasios.setLayout(jPanel_listaGimnasiosLayout);
        jPanel_listaGimnasiosLayout.setHorizontalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_listaGimnasios, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listaGimnasiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_lista_actualiza)))
                .addContainerGap())
        );
        jPanel_listaGimnasiosLayout.setVerticalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_listaGimnasios, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_lista_actualiza)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Gimnasios", jPanel_listaGimnasios);

        jLabel_busqueda_nombre.setText("Ingrese el nombre del gimnasio");

        jList_busqueda_nombre.setModel(new DefaultListModel<String>());
        jScrollPane_busqueda_gimnasios.setViewportView(jList_busqueda_nombre);

        jLabel1.setText("Editar Gimnasio");

        jLabel_editar_id.setText("ID Gimnasio");

        jLabel_editar_nombre.setText("Nombre");

        jLabel_editar_maquinas.setText("N° de máquinas");

        jLabel_editar_crossfit.setText("Incluye Crossfit");

        jLabel_editar_promedio.setText("Promedio mensual de clientes");

        jButton_buscar_nombre.setText("Buscar");
        jButton_buscar_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_buscar_nombreMouseClicked(evt);
            }
        });

        jButton_editar_guardar_cambios1.setText("Guardar cambios");
        jButton_editar_guardar_cambios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_editar_guardar_cambios1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_buscarGimnasiosLayout = new javax.swing.GroupLayout(jPanel_buscarGimnasios);
        jPanel_buscarGimnasios.setLayout(jPanel_buscarGimnasiosLayout);
        jPanel_buscarGimnasiosLayout.setHorizontalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_busqueda_gimnasios)
                    .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                        .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_busqueda_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_busqueda_nombre))
                                .addGap(30, 30, 30)
                                .addComponent(jButton_buscar_nombre))
                            .addComponent(jLabel1)
                            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                                        .addComponent(jLabel_editar_id)
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_editar_nombre)
                                            .addComponent(jTextField_editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextField_editar_id, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_editar_maquinas)
                                    .addComponent(jTextField_editar_maquinas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_editar_crossfit)
                                    .addComponent(jCheckBox_editar_crossfit))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_editar_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_editar_promedio)))
                            .addComponent(jButton_editar_guardar_cambios1))
                        .addGap(0, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_buscarGimnasiosLayout.setVerticalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_buscarGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_busqueda_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_busqueda_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_busqueda_gimnasios, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_editar_id)
                    .addComponent(jLabel_editar_nombre)
                    .addComponent(jLabel_editar_maquinas)
                    .addComponent(jLabel_editar_crossfit)
                    .addComponent(jLabel_editar_promedio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_editar_promedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_editar_crossfit, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_editar_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_editar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_editar_maquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton_editar_guardar_cambios1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Búsqueda de Gimnasios", jPanel_buscarGimnasios);

        jLabel_promedioMinimo.setText("Ingrese el promedio mínimo para el filtro de gimnasios");

        jButton_filtrarPorPromedio.setText("Filtrar");
        jButton_filtrarPorPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_filtrarPorPromedioMouseClicked(evt);
            }
        });

        jList_busqueda_promedio.setModel(new DefaultListModel<String>());
        jScrollPane1.setViewportView(jList_busqueda_promedio);

        javax.swing.GroupLayout jPanel_busquedaPorClientesLayout = new javax.swing.GroupLayout(jPanel_busquedaPorClientes);
        jPanel_busquedaPorClientes.setLayout(jPanel_busquedaPorClientesLayout);
        jPanel_busquedaPorClientesLayout.setHorizontalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                        .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_promedioMinimo)
                            .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_filtrarPorPromedio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 670, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_busquedaPorClientesLayout.setVerticalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_promedioMinimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_filtrarPorPromedio)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Búsqueda por Promedio de Clientes", jPanel_busquedaPorClientes);

        jButton_ordenarNombre.setText("Ordenar por nombre");

        jButton_ordenarNumMaquinas.setText("Ordernar por cantidad de máquinas");

        javax.swing.GroupLayout jPanel_ordenarGimnasiosLayout = new javax.swing.GroupLayout(jPanel_ordenarGimnasios);
        jPanel_ordenarGimnasios.setLayout(jPanel_ordenarGimnasiosLayout);
        jPanel_ordenarGimnasiosLayout.setHorizontalGroup(
            jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ordenarGimnasiosLayout.createSequentialGroup()
                .addContainerGap(588, Short.MAX_VALUE)
                .addComponent(jButton_ordenarNumMaquinas)
                .addGap(18, 18, 18)
                .addComponent(jButton_ordenarNombre)
                .addContainerGap())
        );
        jPanel_ordenarGimnasiosLayout.setVerticalGroup(
            jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ordenarGimnasiosLayout.createSequentialGroup()
                .addContainerGap(609, Short.MAX_VALUE)
                .addGroup(jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ordenarNombre)
                    .addComponent(jButton_ordenarNumMaquinas))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordenamiento de Gimnasios", jPanel_ordenarGimnasios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox_crossfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_crossfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_crossfitActionPerformed

    private void jButton_anadir_gymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anadir_gymMouseClicked
        String nombre = jTextField_nombre_gym.getText();
        int maquinas = Integer.parseInt(jTextField_cantidad_maqinas.getText());
        boolean crossfit = jCheckBox_crossfit.isSelected();
        int clientes = Integer.parseInt(jTextField_cant_clientes.getText());
        int id = gymDao.gymIdsContador;

        gymDao.anadirGimnasio(id, nombre, maquinas, crossfit, clientes);
        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        
    }//GEN-LAST:event_jButton_anadir_gymMouseClicked

    private void jButton_anadir_gymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anadir_gymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_anadir_gymActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_buscar_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscar_nombreMouseClicked
        ArrayList<Gimnasio> listaGimnasios = gymDao.EncuentraPorNombre(jTextField_busqueda_nombre.getText());
        DefaultListModel<String> listModel = new DefaultListModel();
        
        for (Gimnasio gimnasio : listaGimnasios) {
            listModel.addElement("ID: " + gimnasio.getId() + "   |    Nombre: " + gimnasio.getNombre() + "   |    Número de máquinas: " + gimnasio.getNumeroMaquinas() + "   |    Incluye crossfit: " + gimnasio.getIncluyeCrossfit() + "   |    Promedio clientes por mes: " + gimnasio.getClientesPorMes());
        }

        jList_busqueda_nombre.setModel(listModel);
    }//GEN-LAST:event_jButton_buscar_nombreMouseClicked

    private void jButton_editar_guardar_cambios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_editar_guardar_cambios1MouseClicked
        int id = Integer.parseInt(jTextField_editar_id.getText());
        String nombre = jTextField_editar_nombre.getText();
        int maquinas = Integer.parseInt(jTextField_editar_maquinas.getText());
        boolean crossfit = jCheckBox_editar_crossfit.isSelected();
        int clientes = Integer.parseInt(jTextField_editar_promedio.getText());
        
        Gimnasio nuevosDatos = new Gimnasio(id, nombre, maquinas, crossfit, clientes);

        gymDao.ActualizarGimnasio(nuevosDatos);

    }//GEN-LAST:event_jButton_editar_guardar_cambios1MouseClicked

    private void jButton_lista_actualizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_lista_actualizaMouseClicked
        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
    }//GEN-LAST:event_jButton_lista_actualizaMouseClicked

    private void jButton_filtrarPorPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_filtrarPorPromedioMouseClicked
        ArrayList<Gimnasio> listaGimnasios = gymDao.FiltrarPorPromedio(Integer.parseInt(jTextField_promedioClientes.getText()));
        DefaultListModel<String> listModel = new DefaultListModel();
        
        for (Gimnasio gimnasio : listaGimnasios) {
            listModel.addElement("ID: " + gimnasio.getId() + "   |    Nombre: " + gimnasio.getNombre() + "   |    Número de máquinas: " + gimnasio.getNumeroMaquinas() + "   |    Incluye crossfit: " + gimnasio.getIncluyeCrossfit() + "   |    Promedio clientes por mes: " + gimnasio.getClientesPorMes());
        }
        jList_busqueda_promedio.setModel(listModel);
    }//GEN-LAST:event_jButton_filtrarPorPromedioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_anadir_gym;
    private javax.swing.JButton jButton_buscar_nombre;
    private javax.swing.JButton jButton_editar_guardar_cambios1;
    private javax.swing.JButton jButton_filtrarPorPromedio;
    private javax.swing.JButton jButton_lista_actualiza;
    private javax.swing.JButton jButton_ordenarNombre;
    private javax.swing.JButton jButton_ordenarNumMaquinas;
    private javax.swing.JCheckBox jCheckBox_crossfit;
    private javax.swing.JCheckBox jCheckBox_editar_crossfit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_busqueda_nombre;
    private javax.swing.JLabel jLabel_cant_clientes;
    private javax.swing.JLabel jLabel_cantidad_maquinas;
    private javax.swing.JLabel jLabel_editar_crossfit;
    private javax.swing.JLabel jLabel_editar_id;
    private javax.swing.JLabel jLabel_editar_maquinas;
    private javax.swing.JLabel jLabel_editar_nombre;
    private javax.swing.JLabel jLabel_editar_promedio;
    private javax.swing.JLabel jLabel_nombre_gym;
    private javax.swing.JLabel jLabel_promedioMinimo;
    private javax.swing.JLabel jLabel_tituloPrincipal;
    private javax.swing.JList<String> jList_busqueda_nombre;
    private javax.swing.JList<String> jList_busqueda_promedio;
    private javax.swing.JPanel jPanel_anadirGimnasio;
    private javax.swing.JPanel jPanel_buscarGimnasios;
    private javax.swing.JPanel jPanel_busquedaPorClientes;
    private javax.swing.JPanel jPanel_listaGimnasios;
    private javax.swing.JPanel jPanel_ordenarGimnasios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_busqueda_gimnasios;
    private javax.swing.JScrollPane jScrollPane_listaGimnasios;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_tablaListaGimnasios;
    private javax.swing.JTextField jTextField_busqueda_nombre;
    private javax.swing.JTextField jTextField_cant_clientes;
    private javax.swing.JTextField jTextField_cantidad_maqinas;
    private javax.swing.JTextField jTextField_editar_id;
    private javax.swing.JTextField jTextField_editar_maquinas;
    private javax.swing.JTextField jTextField_editar_nombre;
    private javax.swing.JTextField jTextField_editar_promedio;
    private javax.swing.JTextField jTextField_nombre_gym;
    private javax.swing.JTextField jTextField_promedioClientes;
    // End of variables declaration//GEN-END:variables
}
