/*
 * @author Jose Luis Mora
 */
public class MainUIFrame extends javax.swing.JFrame {
    
    // Inicializa el DAO para los gimnasios
    GimnasioDAO gymDao = new GimnasioDAO();

    /**
     * Creates new form MainUIFrame
     */
    public MainUIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_tituloPrincipal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_anadirGimnasio = new javax.swing.JPanel();
        jLabel_nombre_gym = new javax.swing.JLabel();
        jTextField_nombre_gym = new javax.swing.JTextField();
        jLabel_cantidad_maquinas = new javax.swing.JLabel();
        jTextField_cantidad_maqinas = new javax.swing.JTextField();
        jCheckBox_crossfit = new javax.swing.JCheckBox();
        jLabel_cant_clientes = new javax.swing.JLabel();
        jTextField_cant_clientes = new javax.swing.JTextField();
        jButton_anadir_gym = new javax.swing.JButton();
        jPanel_listaGimnasios = new javax.swing.JPanel();
        jScrollPane_listaGimnasios = new javax.swing.JScrollPane();
        jTable_tablaListaGimnasios = new javax.swing.JTable(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        jButton_actualizaLista = new javax.swing.JButton();
        jPanel_buscarGimnasios = new javax.swing.JPanel();
        jPanel_busquedaPorClientes = new javax.swing.JPanel();
        jLabel_promedioMinimo = new javax.swing.JLabel();
        jTextField_promedioClientes = new javax.swing.JTextField();
        jButton_filtrarPorPromedio = new javax.swing.JButton();
        jScrollPane_filtroPorPromedio = new javax.swing.JScrollPane();
        jTable_filtroPorPromedio = new javax.swing.JTable();
        jPanel_ordenarGimnasios = new javax.swing.JPanel();
        jButton_ordenarNombre = new javax.swing.JButton();
        jButton_ordenarNumMaquinas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_tituloPrincipal.setText("Asociación Nacional de Gimnasios y Centros de Salud");

        jButton1.setText("Ok");
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTabbedPane1.setName(""); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel_anadirGimnasio.setPreferredSize(new java.awt.Dimension(792, 329));

        jLabel_nombre_gym.setText("Nombre del Gimnasio");

        jLabel_cantidad_maquinas.setText("Cantidad de Máquinas");

        jCheckBox_crossfit.setText("Incluye Crossfit");
        jCheckBox_crossfit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_crossfitActionPerformed(evt);
            }
        });

        jLabel_cant_clientes.setText("Cantidad promedio de clientes mensuales");

        jButton_anadir_gym.setText("Añadir Gimnasio");
        jButton_anadir_gym.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_anadir_gymMouseClicked(evt);
            }
        });
        jButton_anadir_gym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anadir_gymActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_anadirGimnasioLayout = new javax.swing.GroupLayout(jPanel_anadirGimnasio);
        jPanel_anadirGimnasio.setLayout(jPanel_anadirGimnasioLayout);
        jPanel_anadirGimnasioLayout.setHorizontalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombre_gym, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_cantidad_maquinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                        .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_nombre_gym, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox_crossfit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                .addComponent(jTextField_cantidad_maqinas, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_anadir_gym)
                                .addComponent(jTextField_cant_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 598, Short.MAX_VALUE))
                    .addComponent(jLabel_cant_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_anadirGimnasioLayout.setVerticalGroup(
            jPanel_anadirGimnasioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_anadirGimnasioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_nombre_gym)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_nombre_gym, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cantidad_maquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cantidad_maqinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_crossfit)
                .addGap(18, 18, 18)
                .addComponent(jLabel_cant_clientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_cant_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_anadir_gym)
                .addContainerGap(375, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Añadir Gimnasio", jPanel_anadirGimnasio);

        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        jScrollPane_listaGimnasios.setViewportView(jTable_tablaListaGimnasios);

        jButton_actualizaLista.setText("(DEPRECATED) Actualizar Lista");
        jButton_actualizaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_actualizaListaMouseClicked(evt);
            }
        });
        jButton_actualizaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizaListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_listaGimnasiosLayout = new javax.swing.GroupLayout(jPanel_listaGimnasios);
        jPanel_listaGimnasios.setLayout(jPanel_listaGimnasiosLayout);
        jPanel_listaGimnasiosLayout.setHorizontalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_listaGimnasios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_listaGimnasiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_actualizaLista)))
                .addContainerGap())
        );
        jPanel_listaGimnasiosLayout.setVerticalGroup(
            jPanel_listaGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_listaGimnasiosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_listaGimnasios, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton_actualizaLista)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Gimnasios", jPanel_listaGimnasios);

        javax.swing.GroupLayout jPanel_buscarGimnasiosLayout = new javax.swing.GroupLayout(jPanel_buscarGimnasios);
        jPanel_buscarGimnasios.setLayout(jPanel_buscarGimnasiosLayout);
        jPanel_buscarGimnasiosLayout.setHorizontalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        jPanel_buscarGimnasiosLayout.setVerticalGroup(
            jPanel_buscarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Búsqueda de Gimnasios", jPanel_buscarGimnasios);

        jLabel_promedioMinimo.setText("Ingrese el promedio mínimo para el filtro de gimnasios");

        jButton_filtrarPorPromedio.setText("Filtrar");

        jScrollPane_filtroPorPromedio.setViewportView(jTable_filtroPorPromedio);

        javax.swing.GroupLayout jPanel_busquedaPorClientesLayout = new javax.swing.GroupLayout(jPanel_busquedaPorClientes);
        jPanel_busquedaPorClientes.setLayout(jPanel_busquedaPorClientesLayout);
        jPanel_busquedaPorClientesLayout.setHorizontalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_filtroPorPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                    .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                        .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_promedioMinimo)
                            .addGroup(jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton_filtrarPorPromedio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel_busquedaPorClientesLayout.setVerticalGroup(
            jPanel_busquedaPorClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_busquedaPorClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_promedioMinimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_promedioClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_filtrarPorPromedio)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_filtroPorPromedio, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Búsqueda por Promedio de Clientes", jPanel_busquedaPorClientes);

        jButton_ordenarNombre.setText("Ordenar por nombre");

        jButton_ordenarNumMaquinas.setText("Ordernar por cantidad de máquinas");

        javax.swing.GroupLayout jPanel_ordenarGimnasiosLayout = new javax.swing.GroupLayout(jPanel_ordenarGimnasios);
        jPanel_ordenarGimnasios.setLayout(jPanel_ordenarGimnasiosLayout);
        jPanel_ordenarGimnasiosLayout.setHorizontalGroup(
            jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ordenarGimnasiosLayout.createSequentialGroup()
                .addContainerGap(588, Short.MAX_VALUE)
                .addComponent(jButton_ordenarNumMaquinas)
                .addGap(18, 18, 18)
                .addComponent(jButton_ordenarNombre)
                .addContainerGap())
        );
        jPanel_ordenarGimnasiosLayout.setVerticalGroup(
            jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ordenarGimnasiosLayout.createSequentialGroup()
                .addContainerGap(591, Short.MAX_VALUE)
                .addGroup(jPanel_ordenarGimnasiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ordenarNombre)
                    .addComponent(jButton_ordenarNumMaquinas))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ordenamiento de Gimnasios", jPanel_ordenarGimnasios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_tituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_tituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox_crossfitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_crossfitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_crossfitActionPerformed

    private void jButton_anadir_gymMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_anadir_gymMouseClicked
        String nombre = jTextField_nombre_gym.getText();
        int maquinas = Integer.parseInt(jTextField_cantidad_maqinas.getText());
        boolean crossfit = jCheckBox_crossfit.isSelected();
        int clientes = Integer.parseInt(jTextField_cant_clientes.getText());
        int id = gymDao.gymIdsContador;

        gymDao.anadirGimnasio(id, nombre, maquinas, crossfit, clientes);
        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
        
    }//GEN-LAST:event_jButton_anadir_gymMouseClicked

    private void jButton_anadir_gymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anadir_gymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_anadir_gymActionPerformed

    private void jButton_actualizaListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_actualizaListaMouseClicked
        jTable_tablaListaGimnasios.setModel(new ListaGimnasios(gymDao.obtenerGimnasios().iterator()));
    }//GEN-LAST:event_jButton_actualizaListaMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton_actualizaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizaListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_actualizaListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_actualizaLista;
    private javax.swing.JButton jButton_anadir_gym;
    private javax.swing.JButton jButton_filtrarPorPromedio;
    private javax.swing.JButton jButton_ordenarNombre;
    private javax.swing.JButton jButton_ordenarNumMaquinas;
    private javax.swing.JCheckBox jCheckBox_crossfit;
    private javax.swing.JLabel jLabel_cant_clientes;
    private javax.swing.JLabel jLabel_cantidad_maquinas;
    private javax.swing.JLabel jLabel_nombre_gym;
    private javax.swing.JLabel jLabel_promedioMinimo;
    private javax.swing.JLabel jLabel_tituloPrincipal;
    private javax.swing.JPanel jPanel_anadirGimnasio;
    private javax.swing.JPanel jPanel_buscarGimnasios;
    private javax.swing.JPanel jPanel_busquedaPorClientes;
    private javax.swing.JPanel jPanel_listaGimnasios;
    private javax.swing.JPanel jPanel_ordenarGimnasios;
    private javax.swing.JScrollPane jScrollPane_filtroPorPromedio;
    private javax.swing.JScrollPane jScrollPane_listaGimnasios;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_filtroPorPromedio;
    private javax.swing.JTable jTable_tablaListaGimnasios;
    private javax.swing.JTextField jTextField_cant_clientes;
    private javax.swing.JTextField jTextField_cantidad_maqinas;
    private javax.swing.JTextField jTextField_nombre_gym;
    private javax.swing.JTextField jTextField_promedioClientes;
    // End of variables declaration//GEN-END:variables
}
